# Unique contribution: HeerakKashyap 2024-05-18 15:30
# Path to the dataset
input: data/dataset.csv

# Target column for prediction
target: label

# Model configuration
model:
  type: classification
  algorithm: RandomForestClassifier
  params:
    n_estimators: 100
    max_depth: 5 